### ISSUE TITLE
Add ansible-lint to pre-commit and fix issues

### ISSUE THREAD

**Issue by kdowney-lot49** [0xg0nz0/homelab#18]
Pre-commit hook:

```
- repo: https://github.com/ansible/ansible-lint
  rev: ... # put latest release tag from https://github.com/ansible/ansible-lint/releases/
  hooks:
    - id: ansible-lint
```
